image:
  repository: documind/api
  tag: "0.1.0"
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 8000

env:
  databaseUrlSecret: documind-database-url
  redisUrlSecret: documind-redis-url
  minioEndpointSecret: documind-minio-endpoint

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: "2"
    memory: 4Gi
